/* ============================================================
   LARS RÉSONANCE — content & data, separated from logic
   ES module: import { DATA } from './data.js'
   ============================================================ */
export const DATA = {

  /* Weather + hours: Stockholm. Open-Meteo needs no API key. */
  location: {
    label: 'Stockholm',
    latitude: 59.33,
    longitude: 18.07,
    timeZone: 'Europe/Stockholm',
    openHour: 9,
    closeHour: 18,
  },

  /* Concierge chat backend. Leave null for the built-in scripted replies; set to a
     URL (e.g. '/api/chat') and modules/chat.js POSTs { lang, messages } and expects { reply }.
     API keys belong on that server, never here. */
  chatEndpoint: null,

  /* Contact form backend. null = simulated success (no request). Set to a URL such as a
     Formspree endpoint ('https://formspree.io/f/xxxx') or your own API; the form POSTs JSON. */
  formEndpoint: null,

  /* Currency conversion, relative to EUR (approximate, display only) */
  baseCurrency: 'EUR',
  currencies: {
    EUR: { rate: 1,     symbol: '€',  position: 'before', locale: 'de-DE' },
    USD: { rate: 1.08,  symbol: '$',  position: 'before', locale: 'en-US' },
    GBP: { rate: 0.85,  symbol: '£',  position: 'before', locale: 'en-GB' },
    SEK: { rate: 11.3,  symbol: ' kr', position: 'after', locale: 'sv-SE' },
  },

  /* ---- Translations ----
     English lives in index.html (the source). Every translatable element carries
     data-i18n="key" (text), data-i18n-html="key" (markup), data-i18n-aria / data-i18n-placeholder.
     Swedish overrides are keyed below; a missing key simply falls back to English. */
  i18n: {
    sv: {
      keyed: {
        "nav.visit": "Boka besök",
        "nav.search": "Sök",
        "nav.saved": "Sparat",
        "settings.title": "Inställningar",
        "settings.language": "Språk",
        "settings.currency": "Valuta",
        "settings.theme": "Tema",
        "settings.effects": "Effekter",
        "settings.light": "Ljust",
        "settings.dark": "Mörkt",
        "settings.lite": "Lite",
        "settings.standard": "Standard",
        "settings.premium": "Premium",
        "legal.privacy": "Integritetspolicy",
        "legal.terms": "Användarvillkor",
        "chat.title": "Résonance Concierge",
        "chat.chip.pianos": "Flyglar & pianon",
        "chat.chip.studio": "Monitorer & mixerbord",
        "chat.chip.book": "Boka visning",
        "chat.chip.contact": "Kontakt",
        "nav.home": "Hem",
        "nav.atelier": "Ateljén",
        "nav.contact": "Kontakt",
        "nav.collection": "Samlingen",
        "nav.spaces": "Rum",
        "nav.services": "Tjänster",
        "nav.reviews": "Omdömen",
        "hero.hand-selected-concert": "Handplockade konsertflyglar och ljud i masteringklass, intonerat av mästartekniker. Från första tangenten till den sista mixen — varje detalj stämd till perfektion.",
        "hero.where-sound": "Där ljudet",
        "hero.becomes": "blir",
        "hero.soul": "själ",
        "collection.a-curated-house": "Ett kurerat hus av konsertflyglar, referensmonitorer, mixerbord och studioinstrument — vart och ett utvalt, intonerat och levererat för hand.",
        "spaces.from-concert-halls": "Från konserthus till privata hem — vi formar instrumentet och akustiken efter varje rum vi rör vid.",
        "about.lars-r-sonance": "Lars Résonance grundades på en enda övertygelse: att ett instrument och rummet det lever i förtjänar samma omsorg som musiken själv. Vi väljer ut konsertflyglar och referensljud från världens främsta tillverkare — och får dem att sjunga.",
        "about.from-a-steinway": "Från en handintonerad Steinway till en masteringstudio stämd på millimetern — våra mästartekniker behandlar varje projekt som ett unikt uppdrag. Inget lämnar ateljén förrän det låter självklart.",
        "stats.instruments-voiced": "Intonerade instrument",
        "stats.studios-designed": "Designade studior",
        "stats.of-craftsmanship": "Av hantverk",
        "stats.master-technicians": "Mästartekniker",
        "stats.yrs": "år",
        "collection.everything": "Allt",
        "collection.pianos-keys": "Pianon & klaviatur",
        "collection.studio-audio": "Studio & ljud",
        "collection.atelier-services": "Ateljétjänster",
        "collection.bespoke-studio-design": "Skräddarsydd studiodesign",
        "collection.analogue-synth-collection": "Analog synthsamling",
        "collection.analogue-mixing-console": "Analogt mixerbord",
        "collection.vintage-tube-microphone": "Vintage rörmikrofon",
        "collection.flagship": "Flaggskepp",
        "collection.reference": "Referens",
        "collection.bespoke": "Skräddarsytt",
        "collection.iconic": "Ikonisk",
        "collection.hand-built": "Handbyggd",
        "collection.legendary": "Legendarisk",
        "spaces.stage": "Scen",
        "spaces.private": "Privat",
        "spaces.academy": "Akademi",
        "spaces.sacred": "Sakralt",
        "spaces.grand": "Storslaget",
        "spaces.intimate": "Intimt",
        "spaces.120-venues": "120+ scener",
        "spaces.240-studios": "240+ studior",
        "spaces.650-homes": "650+ hem",
        "spaces.90-academies": "90+ skolor",
        "spaces.300-spaces": "300+ rum",
        "spaces.75-stages": "75+ studior",
        "spaces.60-houses": "60+ hus",
        "spaces.180-clubs": "180+ klubbar",
        "spaces.140-suites": "140+ studior",
        "testimonials.the-grand-they": "”Flygeln de intonerade för min konsertsal är det finaste instrument jag någonsin spelat. Varje register sjunger — anslaget är självklart och tonen bara strömmar ut.”",
        "testimonials.they-designed-our": "”De formgav hela vårt masteringrum — akustik, monitorer, mixerbord, allt. För första gången är det jag hör i studion exakt det som hamnar på skivan.”",
        "testimonials.from-the-first": "”Från första telefonsamtalet till den sista intoneringen i mitt hem var omsorgen om detaljerna enastående. Det här är ett hus som behandlar ljud som en konstform.”",
        "makers.the-makers-we": "Tillverkarna vi representerar",
        "press.as-featured-in": "Omskrivna i",
        "recent.recently-viewed": "Nyligen visade",
        "recent.clear": "Rensa",
        "contact.visit-the-atelier": "Besök ateljén för en privat visning, eller bjud in oss till ditt rum. Vi lyssnar på vad du behöver och föreslår ett instrument eller en studio helt komponerad för dig — utan förpliktelse.",
        "hero.the-collection": "Samlingen",
        "hero.our-craft": "Vårt hantverk",
        "about.book-a-private": "Boka en privat visning",
        "collection.view-the-full": "Se hela katalogen",
        "luxury-cta.book-a-private": "Boka en privat visning",
        "contact.request-a-private": "Boka en privat visning",
        "dossier.enquire": "Förfrågan",
        "dossier.save": "Spara",
        "contact.preferred-date-private": "Önskat datum — privat visning",
        "contact.choose-a-time": "Välj en tid",
        "footer.a-bespoke-atelier": "En skräddarsydd ateljé för konsertflyglar och high-end-ljud. Ljud, fulländat för hand.",
        "hero.play-a-note": "Spela en ton",
        "dossier.provenance": "Proveniens",
        "drawer.nothing-saved-yet": "Inget sparat än. Tryck på hjärtat på valfritt instrument för att spara det här.",
        "search-overlay.search-the-collection": "Sök i samlingen",
        "about.years-of-craftsmanship": "År av<br>hantverk",
        "collection.price-on-request": "Pris på begäran",
        "collection.from-36-500": "Från <span data-eur=\"36500\">€36,500</span> / par",
        "collection.commission-only": "Endast på uppdrag",
        "collection.from-4-200": "Från <span data-eur=\"4200\">€4,200</span>",
        "collection.by-appointment": "Efter överenskommelse",
        "collection.from-9-800": "Från <span data-eur=\"9800\">€9,800</span>",
        "hero.concert-grade": "Konsert<span class=\"mobile-hide\">klass</span>",
        "about.the-atelier": "Ateljén",
        "collection.the-collection": "Samlingen",
        "spaces.spaces-we-tune": "Rum<span class=\"mobile-hide\"> vi stämmer</span>",
        "services.the-craft": "Hantverket",
        "testimonials.in-their-words": "Med deras ord",
        "contact.get-in-touch": "Hör av dig",
        "about.master-technicians": "Mästartekniker",
        "about.concert-level-tuning": "Stämning, intonering och reglering för hand på konsertnivå",
        "about.world-s-finest": "Världens främsta tillverkare",
        "about.an-exclusive-curation": "Ett exklusivt urval av flyglar, mixerbord och referensljud",
        "spaces.concert-halls": "Konserthus",
        "spaces.concert-grands-prepared": "Konsertflyglar förberedda för världens stora scener",
        "spaces.recording-studios": "Inspelningsstudior",
        "spaces.consoles-monitors-and": "Mixerbord, monitorer och mikrofoner för rum i världsklass",
        "spaces.private-residences": "Privata hem",
        "spaces.salon-grands-and": "Salongsflyglar och lyssningsrum för samlare",
        "spaces.conservatories": "Musikhögskolor",
        "spaces.practice-and-performance": "Övnings- och konsertpianon för institutioner",
        "spaces.houses-of-worship": "Kyrkor",
        "spaces.acoustic-instruments-and": "Akustiska instrument och diskreta ljudsystem",
        "spaces.broadcast-film": "Broadcast & film",
        "spaces.scoring-stages-and": "Filmmusikstudior och postproduktion stämda för bild",
        "spaces.opera-ballet": "Opera & balett",
        "spaces.pit-and-stage": "Instrument för orkesterdike och scen i de största produktionerna",
        "spaces.jazz-supper-clubs": "Jazzklubbar",
        "spaces.salon-grands-and-2": "Salongsflyglar och varma rum för intima kvällar",
        "spaces.mastering-suites": "Masteringstudior",
        "spaces.reference-rooms-tuned": "Referensrum stämda för den slutliga mastern",
        "services.bespoke-selection": "Skräddarsytt urval",
        "services.we-listen-first": "Vi lyssnar först. Sedan handplockar vi instrumentet eller systemet som passar ditt anslag, din repertoar och ditt rum — från världens mest ansedda tillverkare.",
        "services.tuning-voicing": "Stämning & intonering",
        "services.concert-level-tuning": "Stämning, reglering och intonering för hand på konsertnivå. Vi formar varje hammare och tangent tills instrumentet svarar exakt som artisten tänker sig.",
        "services.studio-acoustics": "Studio & akustik",
        "services.turnkey-studio-design": "Nyckelfärdig studiodesign — rumsakustik, rumsbehandling, monitorering, mixerbord och kablage. Vi bygger ett rum där varje beslut du tar i mixen blir rätt.",
        "services.white-glove-delivery": "Leverans med silkesvantar",
        "services.climate-controlled-transport": "Klimatstyrd transport, expertinstallation och avslutande intonering på plats — plus livstids eftervård. Ditt instrument anländer spelklart, inte bara levererat.",
        "services.learn-more": "Läs mer",
        "luxury-cta.hear-the-difference": "Hör <em>skillnaden</em>",
        "luxury-cta.whether-it-s": "Oavsett om det är en enda konsertflygel eller en komplett masteringstudio komponerar ateljén en uppsättning helt anpassad efter dig — och levererar den spelklar.",
        "testimonials.concert-pianist": "Konsertpianist",
        "testimonials.mastering-engineer": "Masteringtekniker",
        "testimonials.composer-collector": "Kompositör & samlare",
        "press.musictech-gold-award": "MusicTech Gold Award 2025",
        "press.steinway-certified-atelier": "Steinway-certifierad ateljé",
        "press.40-years-of": "40 år av hantverk",
        "contact.showroom": "Showroom",
        "contact.the-atelier": "Ateljén",
        "contact.call-us": "Ring oss",
        "contact.email": "E-post",
        "footer.collection": "Samlingen",
        "footer.grand-pianos": "Flyglar",
        "footer.synths-keyboards": "Synthar & klaviatur",
        "footer.studio-monitors": "Studiomonitorer",
        "footer.mixing-consoles": "Mixerbord",
        "footer.microphones": "Mikrofoner",
        "footer.spaces": "Rum",
        "footer.concert-halls": "Konserthus",
        "footer.recording-studios": "Inspelningsstudior",
        "footer.private-residences": "Privata hem",
        "footer.conservatories": "Musikhögskolor",
        "footer.broadcast-film": "Broadcast & film",
        "footer.atelier": "Ateljén",
        "footer.our-craft": "Vårt hantverk",
        "footer.tuning-voicing": "Stämning & intonering",
        "footer.studio-design": "Studiodesign",
        "footer.contact": "Kontakt",
        "footer.2026-lars-r": "© 2026 Lars Résonance Atelier. Alla rättigheter förbehållna.",
        "drawer.saved-instruments": "Sparade instrument",
        "contact.mo": "Må",
        "contact.tu": "Ti",
        "contact.we": "On",
        "contact.th": "To",
        "contact.fr": "Fr",
        "contact.sa": "Lö",
        "contact.su": "Sö",
        "collection.view-details": "Visa detaljer",
        "collection.concert-grand": "Konsertflygel",
        "collection.main-monitors-power": "Huvudmonitorer + slutsteg",
        "collection.turnkey-studio-build": "Nyckelfärdig studio",
        "collection.synths-keyboards": "Synthar & klaviatur",
        "collection.mixing-mastering-console": "Mix- & masteringbord",
        "collection.tube-microphone": "Rörmikrofon",
        "contact.first-name": "Förnamn",
        "contact.last-name": "Efternamn",
        "contact.email-address": "E-postadress",
        "contact.phone-number": "Telefonnummer",
        "contact.i-m-interested": "Jag är intresserad av",
        "contact.tell-us-about": "Berätta om ditt projekt",
        "contact.grand-upright-pianos": "Flyglar & pianon",
        "contact.synths-keyboards": "Synthar & klaviatur",
        "contact.monitors-power-amps": "Monitorer & slutsteg",
        "contact.consoles-microphones": "Mixerbord & mikrofoner",
        "contact.full-studio-build": "Komplett studiobygge",
        "collection.hand-voiced": "Handintonerad",
        "collection.spruce": "Gran",
        "collection.3-way": "3-vägs",
        "collection.class-a-amp": "Klass A-steg",
        "collection.acoustics": "Akustik",
        "collection.wiring": "Kablage",
        "collection.treatment": "Rumsbehandling",
        "collection.88-keys": "88 tangenter",
        "collection.polyphonic": "Polyfon",
        "collection.48-ch": "48 kanaler",
        "collection.discrete": "Diskret",
        "collection.cardioid": "Kardioid",
        "collection.tube": "Rör",
        "collection.hand-made": "Handgjord",
        "hero.scroll-to-listen": "Scrolla och lyssna",
        "about.sound-uncompromised": "Ljud, <em>kompromisslöst</em>",
        "collection.instruments-without-equal": "Instrument <em>utan</em> motstycke",
        "spaces.heard-in-the-finest-rooms": "Hörs i de <em>finaste</em> rummen",
        "services.atelier-services": "Ateljéns <em>tjänster</em>",
        "testimonials.trusted-by-artists": "Anlitas av <em>artister</em>",
        "contact.book-a-private-audition": "Boka en <em>privat</em> visning",
        "announce.base": "Privata visningar efter överenskommelse — Strandvägen 7A, Stockholm",
        "nav.search-the-collection": "Sök i samlingen",
        "nav.saved-instruments": "Sparade instrument",
        "nav.settings": "Inställningar",
        "nav.toggle-menu": "Öppna menyn",
        "hero.the-makers-we": "Tillverkarna vi representerar",
        "collection.save-piece": "Spara",
        "collection.recently-viewed": "Nyligen visade",
        "spaces.previous-slide": "Föregående",
        "spaces.next-slide": "Nästa",
        "testimonials.press-and-recognition": "Press och utmärkelser",
        "contact.previous-month": "Föregående månad",
        "contact.next-month": "Nästa månad",
        "footer.effects-level": "Effektnivå",
        "footer.image-gallery": "Bildgalleri",
        "lightbox.close": "Stäng",
        "lightbox.previous-image": "Föregående bild",
        "lightbox.next-image": "Nästa bild",
        "dossier.close": "Stäng",
        "dossier.saved-instruments": "Sparade instrument",
        "drawer.close": "Stäng",
        "drawer.search": "Sök",
        "search-overlay.close-search": "Stäng sökningen",
        "perf-banner.back-to-top": "Till toppen",
        "search-overlay.pianos-monitors-microphones": "Pianon, monitorer, mikrofoner…",
      },
      /* Strings that live in JS (toasts, form states, ambient bar, effects banner) */
      ui: {
        sending: 'Skickar…', received: 'Förfrågan mottagen!',
        formSent: 'Tack — din förfrågan är mottagen. Vi bekräftar din visning inom dagen.',
        formError: 'Något gick fel när meddelandet skickades. Försök igen, eller ring 08-555 01 90.',
        errRequired: 'Fältet är obligatoriskt.', errName: 'Ange minst två tecken.',
        errEmail: 'Ange en giltig e-postadress.', errMessage: 'Berätta lite om ditt projekt (minst 10 tecken).',
        errInterest: 'Välj vad du är intresserad av.',
        saved: 'Sparat — ', removedSaved: 'Borttaget från sparat', clearedRecent: 'Nyligen visade rensat',
        noMatch: 'Inget matchar', instrument: 'instrument',
        save: 'Spara', savedBtn: 'Sparat',
        chooseTime: 'Välj nu en tid.', requested: '✓ Privat visning önskad', at: 'kl.',
        openUntil: 'Ateljén är öppen till', opensAt: 'Ateljén öppnar', weather: 'Lokalt väder',
        tabAway: 'Tills du är tillbaka — Lars Résonance',
        perfHeavy: 'Sidan känns tung på din enhet. Vill du byta till en lättare version för en mjukare upplevelse?',
        perfSwitch: 'Byt till', perfNo: 'Nej tack',
        'tier.lite': 'Lite', 'tier.standard': 'Standard', 'tier.premium': 'Premium',
      },
      /* WMO weather codes for the ambient bar */
      weather: {
        0: 'Klart', 1: 'Mestadels klart', 2: 'Lätta moln', 3: 'Mulet',
        45: 'Dimma', 48: 'Dimma', 51: 'Lätt duggregn', 53: 'Duggregn', 55: 'Duggregn',
        61: 'Lätt regn', 63: 'Regn', 65: 'Kraftigt regn', 71: 'Lätt snö', 73: 'Snö',
        75: 'Kraftig snö', 80: 'Regnskurar', 81: 'Skurar', 82: 'Kraftiga skurar', 95: 'Åska',
      },
      html: {
        'Sound, <em>Uncompromised</em>': 'Ljud, <em>kompromisslöst</em>',
        'Instruments, <em>Without</em> Equal': 'Instrument <em>utan</em> motstycke',
        'Heard In The <em>Finest</em> Rooms': 'Hörs i de <em>finaste</em> rummen',
        'Atelier <em>Services</em>': 'Ateljéns <em>tjänster</em>',
        'Hear The <em>Difference</em>': 'Hör <em>skillnaden</em>',
        'Trusted by <em>Artists</em>': 'Anlitas av <em>artister</em>',
        'Book a <em>Private</em> Audition': 'Boka en <em>privat</em> visning',
        'Years of<br>Craftsmanship': 'År av<br>hantverk',
      },
      text: {
        // Nav
        'Home': 'Hem', 'Atelier': 'Ateljén', 'Collection': 'Samlingen',
        'Services': 'Tjänster', 'Reviews': 'Omdömen', 'Contact': 'Kontakt', 'Spaces': 'Rum',
        // Hero
        'Where Sound': 'Där ljudet', 'Becomes': 'blir', 'Soul': 'själ',
        'Hand-selected concert grands and mastering-grade audio, voiced by master technicians. From the first key to the final mix — every detail tuned to perfection.':
          'Handplockade konsertflyglar och ljud i masteringklass, intonerat av mästartekniker. Från första tangenten till den sista mixen — varje detalj stämd till perfektion.',
        'The Collection': 'Samlingen', 'Our Craft': 'Vårt hantverk', 'Play a note': 'Spela en ton',
        // Makers / press
        'The Makers We Represent': 'Tillverkarna vi representerar',
        'As Featured In': 'Omskrivna i',
        'MusicTech Gold Award 2025': 'MusicTech Gold Award 2025',
        'Steinway Certified Atelier': 'Steinway-certifierad ateljé',
        '40 Years of Craftsmanship': '40 år av hantverk',
        // About
        'The Atelier': 'Ateljén',
        'Lars Résonance was founded on a single conviction: that an instrument and the room it lives in deserve the same obsessive care as the music itself. We curate concert grands and reference audio from the world’s finest makers — then make them sing.':
          'Lars Résonance grundades på en enda övertygelse: att ett instrument och rummet det lever i förtjänar samma omsorg som musiken själv. Vi väljer ut konsertflyglar och referensljud från världens främsta tillverkare — och får dem att sjunga.',
        'From a Steinway voiced by hand to a mastering suite tuned to the millimetre, our master technicians treat every project as a one-off commission. Nothing leaves the atelier until it sounds effortless.':
          'Från en handintonerad Steinway till en masteringstudio stämd på millimetern — våra mästartekniker behandlar varje projekt som ett unikt uppdrag. Inget lämnar ateljén förrän det låter självklart.',
        'Master Technicians': 'Mästartekniker',
        'Concert-level tuning, voicing and regulation by hand': 'Stämning, intonering och reglering för hand på konsertnivå',
        'World’s Finest Makers': 'Världens främsta tillverkare',
        'An exclusive curation of grands, consoles and reference audio': 'Ett exklusivt urval av flyglar, mixerbord och referensljud',
        'Book a Private Audition': 'Boka en privat visning',
        // Stats
        'Instruments Voiced': 'Intonerade instrument', 'Studios Designed': 'Designade studior',
        'Of Craftsmanship': 'Av hantverk', 'Master Technicians ': 'Mästartekniker',
        // Collection
        'A curated house of concert grands, reference monitors, consoles and studio instruments — each selected, voiced and delivered by hand.':
          'Ett kurerat hus av konsertflyglar, referensmonitorer, mixerbord och studioinstrument — vart och ett utvalt, intonerat och levererat för hand.',
        'Everything': 'Allt', 'Pianos & Keys': 'Pianon & klaviatur',
        'Studio & Audio': 'Studio & ljud', 'Atelier Services': 'Ateljétjänster',
        'View the Full Catalogue': 'Se hela katalogen',
        'Recently Viewed': 'Nyligen visade', 'Clear': 'Rensa',
        // Spaces
        'From concert halls to private residences, we craft the instrument and the acoustics to suit every space we touch.':
          'Från konserthus till privata hem — vi formar instrumentet och akustiken efter varje rum vi rör vid.',
        // Services
        'The Craft': 'Hantverket',
        'Bespoke Selection': 'Skräddarsytt urval',
        'Tuning & Voicing': 'Stämning & intonering',
        'Studio & Acoustics': 'Studio & akustik',
        'White-Glove Delivery': 'Leverans med silkesvantar',
        'Learn More': 'Läs mer',
        'Save': 'Spara', 'Saved': 'Sparat', 'Enquire': 'Förfrågan',
        // CTA
        'Whether it’s a single concert grand or a complete mastering suite, our atelier composes a setup tuned entirely to you — and delivers it ready to play.':
          'Oavsett om det är en enda konsertflygel eller en komplett masteringstudio komponerar ateljén en uppsättning helt anpassad efter dig — och levererar den spelklar.',
        // Testimonials
        'In Their Words': 'Med deras ord',
        'Concert Pianist': 'Konsertpianist', 'Mastering Engineer': 'Masteringtekniker',
        'Composer & Collector': 'Kompositör & samlare',
        // Contact
        'Get In Touch': 'Hör av dig',
        'Visit the atelier for a private audition, or invite us to your space. We’ll listen to what you need and propose an instrument or studio composed entirely for you — no obligation.':
          'Besök ateljén för en privat visning, eller bjud in oss till ditt rum. Vi lyssnar på vad du behöver och föreslår ett instrument eller en studio helt komponerad för dig — utan förpliktelse.',
        'Showroom': 'Showroom', 'Call Us': 'Ring oss', 'Email': 'E-post',
        'First Name': 'Förnamn', 'Last Name': 'Efternamn', 'Email Address': 'E-postadress',
        'Phone Number': 'Telefonnummer', 'I’m Interested In': 'Jag är intresserad av',
        'Tell Us About Your Project': 'Berätta om ditt projekt',
        'Request a Private Audition': 'Boka en privat visning',
        'Preferred date — private audition': 'Önskat datum — privat visning',
        'Choose a time': 'Välj en tid',
        // Footer
        'A bespoke atelier for concert grands and high-end audio. Sound, perfected by hand.':
          'En skräddarsydd ateljé för konsertflyglar och high-end-ljud. Ljud, fulländat för hand.',
        'Spaces': 'Rum', 'Company': 'Företag',
        '© 2026 Lars Résonance Atelier. All rights reserved.': '© 2026 Lars Résonance Atelier. Alla rättigheter förbehållna.',
        // Announce base
        'Private auditions by appointment — Strandvägen 7A, Stockholm':
          'Privata visningar efter överenskommelse — Strandvägen 7A, Stockholm',
      },
      /* WMO weather codes for the ambient bar */
      weather: {
        0: 'Klart', 1: 'Mestadels klart', 2: 'Lätta moln', 3: 'Mulet',
        45: 'Dimma', 48: 'Dimma', 51: 'Lätt duggregn', 53: 'Duggregn', 55: 'Duggregn',
        61: 'Lätt regn', 63: 'Regn', 65: 'Kraftigt regn', 71: 'Lätt snö', 73: 'Snö',
        75: 'Kraftig snö', 80: 'Regnskurar', 81: 'Skurar', 82: 'Kraftiga skurar', 95: 'Åska',
      },
      html: {
        'Sound, <em>Uncompromised</em>': 'Ljud, <em>kompromisslöst</em>',
        'Instruments, <em>Without</em> Equal': 'Instrument <em>utan</em> motstycke',
        'Heard In The <em>Finest</em> Rooms': 'Hörs i de <em>finaste</em> rummen',
        'Atelier <em>Services</em>': 'Ateljéns <em>tjänster</em>',
        'Hear The <em>Difference</em>': 'Hör <em>skillnaden</em>',
        'Trusted by <em>Artists</em>': 'Anlitas av <em>artister</em>',
        'Book a <em>Private</em> Audition': 'Boka en <em>privat</em> visning',
        'Years of<br>Craftsmanship': 'År av<br>hantverk',
      },
      text: {
        // Nav
        'Home': 'Hem', 'Atelier': 'Ateljén', 'Collection': 'Samlingen',
        'Services': 'Tjänster', 'Reviews': 'Omdömen', 'Contact': 'Kontakt', 'Spaces': 'Rum',
        // Hero
        'Where Sound': 'Där ljudet', 'Becomes': 'blir', 'Soul': 'själ',
        'Hand-selected concert grands and mastering-grade audio, voiced by master technicians. From the first key to the final mix — every detail tuned to perfection.':
          'Handplockade konsertflyglar och ljud i masteringklass, intonerat av mästartekniker. Från första tangenten till den sista mixen — varje detalj stämd till perfektion.',
        'The Collection': 'Samlingen', 'Our Craft': 'Vårt hantverk', 'Play a note': 'Spela en ton',
        // Makers / press
        'The Makers We Represent': 'Tillverkarna vi representerar',
        'As Featured In': 'Omskrivna i',
        'MusicTech Gold Award 2025': 'MusicTech Gold Award 2025',
        'Steinway Certified Atelier': 'Steinway-certifierad ateljé',
        '40 Years of Craftsmanship': '40 år av hantverk',
        // About
        'The Atelier': 'Ateljén',
        'Lars Résonance was founded on a single conviction: that an instrument and the room it lives in deserve the same obsessive care as the music itself. We curate concert grands and reference audio from the world’s finest makers — then make them sing.':
          'Lars Résonance grundades på en enda övertygelse: att ett instrument och rummet det lever i förtjänar samma omsorg som musiken själv. Vi väljer ut konsertflyglar och referensljud från världens främsta tillverkare — och får dem att sjunga.',
        'From a Steinway voiced by hand to a mastering suite tuned to the millimetre, our master technicians treat every project as a one-off commission. Nothing leaves the atelier until it sounds effortless.':
          'Från en handintonerad Steinway till en masteringstudio stämd på millimetern — våra mästartekniker behandlar varje projekt som ett unikt uppdrag. Inget lämnar ateljén förrän det låter självklart.',
        'Master Technicians': 'Mästartekniker',
        'Concert-level tuning, voicing and regulation by hand': 'Stämning, intonering och reglering för hand på konsertnivå',
        'World’s Finest Makers': 'Världens främsta tillverkare',
        'An exclusive curation of grands, consoles and reference audio': 'Ett exklusivt urval av flyglar, mixerbord och referensljud',
        'Book a Private Audition': 'Boka en privat visning',
        // Stats
        'Instruments Voiced': 'Intonerade instrument', 'Studios Designed': 'Designade studior',
        'Of Craftsmanship': 'Av hantverk', 'Master Technicians ': 'Mästartekniker',
        // Collection
        'A curated house of concert grands, reference monitors, consoles and studio instruments — each selected, voiced and delivered by hand.':
          'Ett kurerat hus av konsertflyglar, referensmonitorer, mixerbord och studioinstrument — vart och ett utvalt, intonerat och levererat för hand.',
        'Everything': 'Allt', 'Pianos & Keys': 'Pianon & klaviatur',
        'Studio & Audio': 'Studio & ljud', 'Atelier Services': 'Ateljétjänster',
        'View the Full Catalogue': 'Se hela katalogen',
        'Recently Viewed': 'Nyligen visade', 'Clear': 'Rensa',
        // Spaces
        'From concert halls to private residences, we craft the instrument and the acoustics to suit every space we touch.':
          'Från konserthus till privata hem — vi formar instrumentet och akustiken efter varje rum vi rör vid.',
        // Services
        'The Craft': 'Hantverket',
        'Bespoke Selection': 'Skräddarsytt urval',
        'Tuning & Voicing': 'Stämning & intonering',
        'Studio & Acoustics': 'Studio & akustik',
        'White-Glove Delivery': 'Leverans med silkesvantar',
        'Learn More': 'Läs mer',
        'Save': 'Spara', 'Saved': 'Sparat', 'Enquire': 'Förfrågan',
        // CTA
        'Whether it’s a single concert grand or a complete mastering suite, our atelier composes a setup tuned entirely to you — and delivers it ready to play.':
          'Oavsett om det är en enda konsertflygel eller en komplett masteringstudio komponerar ateljén en uppsättning helt anpassad efter dig — och levererar den spelklar.',
        // Testimonials
        'In Their Words': 'Med deras ord',
        'Concert Pianist': 'Konsertpianist', 'Mastering Engineer': 'Masteringtekniker',
        'Composer & Collector': 'Kompositör & samlare',
        // Contact
        'Get In Touch': 'Hör av dig',
        'Visit the atelier for a private audition, or invite us to your space. We’ll listen to what you need and propose an instrument or studio composed entirely for you — no obligation.':
          'Besök ateljén för en privat visning, eller bjud in oss till ditt rum. Vi lyssnar på vad du behöver och föreslår ett instrument eller en studio helt komponerad för dig — utan förpliktelse.',
        'Showroom': 'Showroom', 'Call Us': 'Ring oss', 'Email': 'E-post',
        'First Name': 'Förnamn', 'Last Name': 'Efternamn', 'Email Address': 'E-postadress',
        'Phone Number': 'Telefonnummer', 'I’m Interested In': 'Jag är intresserad av',
        'Tell Us About Your Project': 'Berätta om ditt projekt',
        'Request a Private Audition': 'Boka en privat visning',
        'Preferred date — private audition': 'Önskat datum — privat visning',
        'Choose a time': 'Välj en tid',
        // Footer
        'A bespoke atelier for concert grands and high-end audio. Sound, perfected by hand.':
          'En skräddarsydd ateljé för konsertflyglar och high-end-ljud. Ljud, fulländat för hand.',
        'Spaces': 'Rum', 'Company': 'Företag',
        '© 2026 Lars Résonance Atelier. All rights reserved.': '© 2026 Lars Résonance Atelier. Alla rättigheter förbehållna.',
        // Announce base
        'Private auditions by appointment — Strandvägen 7A, Stockholm':
          'Privata visningar efter överenskommelse — Strandvägen 7A, Stockholm',
      },
    },
  },

  /* Per-instrument dossiers, keyed by the card's data-id */
  instruments: {
    'konzert-grand': {
      sv: {
        kicker: 'Konsertflygel',
        price: 'Pris på begäran',
        summary: 'Vår flaggskeppsflygel — ett 280 cm-instrument med handbyggd resonansbotten i gran, intonerad ton för ton för världens stora scener. Mekaniken är reglerad för lättast möjliga anslag utan att förlora ett gram kontroll.',
        provenance: 'Varje flygel väljs ut hos tillverkaren och intoneras och regleras sedan i vår Stockholmsverkstad under sex veckor före leverans.',
        specs: [{ label: 'Längd', value: '280 cm' }, { label: 'Resonansbotten', value: 'Massiv alpgran' }, { label: 'Mekanik', value: 'Handreglerad, konsertklass' }, { label: 'Finish', value: 'Handpolerad ebenholts' }, { label: 'Intonering', value: 'Skräddarsydd, efter överenskommelse' }],
      },
      kicker: 'Concert Grand',
      title: 'Konzert Grand 280',
      price: 'Price on Request',
      summary: 'Our flagship concert grand — a 280 cm instrument with a hand-built spruce soundboard, voiced note by note for the world’s great stages. The action is regulated for the lightest possible touch without losing a gram of control.',
      specs: [
        { label: 'Length', value: '280 cm' },
        { label: 'Soundboard', value: 'Solid Alpine spruce' },
        { label: 'Action', value: 'Hand-regulated, concert-grade' },
        { label: 'Finish', value: 'Hand-polished ebony' },
        { label: 'Voicing', value: 'Bespoke, by appointment' },
      ],
      provenance: 'Each grand is selected at the maker’s atelier, then voiced and regulated in our Stockholm workshop over a period of six weeks before delivery.',
      gallery: [
        'https://images.unsplash.com/photo-1520523839897-bd0b52f945a0',
        'https://images.unsplash.com/photo-1552422535-c45813c61732',
        'https://images.unsplash.com/photo-1507676184212-d03ab07a01bf',
      ],
    },
    'reference-monitors': {
      sv: {
        kicker: 'Huvudmonitorer + slutsteg',
        price: 'Från <span data-eur="36500">€36,500</span> / par',
        summary: 'Ett trevägs referenssystem för monitorering, parat med ett dedikerat klass A-slutsteg. Konstruerat för det sista ordet i en mix — rakt, snabbt och skoningslöst avslöjande från 20 Hz till 40 kHz.',
        provenance: 'Levereras som ett kalibrerat par och stäms till rummets akustik vid installationen.',
        specs: [{ label: 'Konfiguration', value: '3-vägs aktiv' }, { label: 'Förstärkare', value: 'Dedikerad klass A' }, { label: 'Frekvensgång', value: '20 Hz – 40 kHz' }, { label: 'Kabinett', value: 'CNC-fräst hårdträ' }, { label: 'Kalibrering', value: 'Rumsanpassad på plats' }],
      },
      kicker: 'Main Monitors + Power Amp',
      title: 'Référence Monitor System',
      price: 'From <span data-eur="36500">€36,500</span> / pair',
      summary: 'A three-way reference monitoring system paired with a dedicated Class-A power amplifier. Engineered for the final word in a mix — flat, fast and utterly revealing from 20 Hz to 40 kHz.',
      specs: [
        { label: 'Configuration', value: '3-way active' },
        { label: 'Amplifier', value: 'Dedicated Class-A' },
        { label: 'Response', value: '20 Hz – 40 kHz' },
        { label: 'Cabinet', value: 'CNC-milled hardwood' },
        { label: 'Calibration', value: 'Room-tuned on site' },
      ],
      provenance: 'Supplied as a calibrated pair and tuned to your room’s acoustics during installation.',
      gallery: [
        'https://images.unsplash.com/photo-1470019693664-1d202d2c0907',
        'https://images.unsplash.com/photo-1466428996289-fb355538da1b',
        'https://images.unsplash.com/photo-1607968565043-36af90dde238',
      ],
    },
    'studio-design': {
      sv: {
        kicker: 'Nyckelfärdig studio',
        price: 'Endast på uppdrag',
        summary: 'En komplett, nyckelfärdig studio — rumsakustik, behandling, monitorering, mixerbord och kablage, ritad och byggd kring hur du arbetar. Vi konstruerar ett rum där varje beslut du tar i mixen blir det rätta.',
        provenance: 'Levereras som ett enda uppdrag, från första akustiska besiktning till slutlig intonering i det färdiga rummet.',
        specs: [{ label: 'Omfattning', value: 'Akustik → kablage' }, { label: 'Behandling', value: 'Skräddarsydd diffusion & absorption' }, { label: 'Monitorering', value: 'Kalibrerad till rummet' }, { label: 'Tidplan', value: 'Normalt 12–20 veckor' }, { label: 'Eftervård', value: 'Livstids support' }],
      },
      kicker: 'Turnkey Studio Build',
      title: 'Bespoke Studio Design',
      price: 'Commission Only',
      summary: 'A complete, turnkey studio — room acoustics, treatment, monitoring, console and wiring, designed and built around the way you work. We engineer a space where every decision you make on the mix is the right one.',
      specs: [
        { label: 'Scope', value: 'Acoustics → wiring' },
        { label: 'Treatment', value: 'Bespoke diffusion & absorption' },
        { label: 'Monitoring', value: 'Calibrated to room' },
        { label: 'Timeline', value: 'Typically 12–20 weeks' },
        { label: 'Aftercare', value: 'Lifetime support' },
      ],
      provenance: 'Delivered as a single commission, from first acoustic survey to final voicing in the finished room.',
      gallery: [
        'https://images.unsplash.com/photo-1564186763535-ebb21ef5277f',
        'https://images.unsplash.com/photo-1516280440614-37939bbacd81',
        'https://images.unsplash.com/photo-1605020420620-20c943cc4669',
      ],
    },
    'synth-collection': {
      sv: {
        kicker: 'Synthar & klaviatur',
        price: 'Från <span data-eur="4200">€4,200</span>',
        summary: 'En kurerad samling analoga synthar och vägda klaviaturer — från ikoniska polyfona klassiker till moderna 88-tangenters kontroller. Varje enhet är servad, kalibrerad och spelklar.',
        provenance: 'Inköpta och renoverade i egen verkstad; varje instrument bänktestas innan det lämnar ateljén.',
        specs: [{ label: 'Typ', value: 'Analog & hybrid' }, { label: 'Tangenter', value: 'Upp till 88, vägda' }, { label: 'Röster', value: 'Mono till fullt polyfon' }, { label: 'Service', value: 'Kalibrerad & med garanti' }],
      },
      kicker: 'Synths & Keyboards',
      title: 'Analogue Synth Collection',
      price: 'From <span data-eur="4200">€4,200</span>',
      summary: 'A curated collection of analogue synthesizers and weighted keyboards — from iconic polyphonic classics to modern 88-key controllers. Each unit is serviced, calibrated and ready to perform.',
      specs: [
        { label: 'Type', value: 'Analogue & hybrid' },
        { label: 'Keys', value: 'Up to 88, weighted' },
        { label: 'Voices', value: 'Mono to fully polyphonic' },
        { label: 'Service', value: 'Calibrated & warrantied' },
      ],
      provenance: 'Sourced and restored in-house; every instrument is bench-tested before it leaves the atelier.',
      gallery: [
        'https://images.unsplash.com/photo-1535992165812-68d1861aa71e',
        'https://images.unsplash.com/photo-1598653222000-6b7b7a552625',
        'https://images.unsplash.com/photo-1574169208507-84376144848b',
      ],
    },
    'mixing-console': {
      sv: {
        kicker: 'Mix- & masteringbord',
        price: 'Efter överenskommelse',
        summary: 'Ett handbyggt analogt 48-kanalsbord med diskret signalväg och total recall. Mittpunkten i ett seriöst rum — värme och headroom i lika mått, byggt för att överleva skivorna som görs på det.',
        provenance: 'Byggs på beställning och tas i drift på plats, med full kalibrering och operatörsutbildning.',
        specs: [{ label: 'Kanaler', value: '48' }, { label: 'Signalväg', value: 'Helt diskret' }, { label: 'Recall', value: 'Total, motoriserad' }, { label: 'Konstruktion', value: 'Handmonterad' }, { label: 'Leveranstid', value: 'Byggs på beställning' }],
      },
      kicker: 'Mixing & Mastering Console',
      title: 'Analogue Mixing Console',
      price: 'By Appointment',
      summary: 'A hand-built 48-channel analogue console with discrete signal path and total recall. The centrepiece of a serious room — warmth and headroom in equal measure, built to outlast the records made on it.',
      specs: [
        { label: 'Channels', value: '48' },
        { label: 'Signal path', value: 'Fully discrete' },
        { label: 'Recall', value: 'Total, motorised' },
        { label: 'Build', value: 'Hand-assembled' },
        { label: 'Lead time', value: 'Made to order' },
      ],
      provenance: 'Built to order and commissioned on site, with full calibration and operator training included.',
      gallery: [
        'https://images.unsplash.com/photo-1493676304819-0d7a8d026dcf',
        'https://images.unsplash.com/photo-1598488035139-bdbb2231ce04',
        'https://images.unsplash.com/photo-1571327073757-71d13c24de30',
      ],
    },
    'tube-mic': {
      sv: {
        kicker: 'Rörmikrofon',
        price: 'Från <span data-eur="9800">€9,800</span>',
        summary: 'En handgjord stormembransmikrofon med rör i den stora traditionen — silkig diskant, rik kropp och en närvaro som definierat skivor i sjuttio år. Levereras med matchad nätdel och skräddarsydd upphängning.',
        provenance: 'Varje mikrofon är handbyggd och testas individuellt mot en referens före leverans.',
        specs: [{ label: 'Kapsel', value: 'Stormembran' }, { label: 'Karakteristik', value: 'Kardioid (flera mönster finns)' }, { label: 'Rör', value: 'Handselekterat' }, { label: 'Ingår', value: 'Nätdel, upphängning, väska' }],
      },
      kicker: 'Tube Microphone',
      title: 'Vintage Tube Microphone',
      price: 'From <span data-eur="9800">€9,800</span>',
      summary: 'A hand-made large-diaphragm tube microphone in the great tradition — silky top end, rich body and a presence that has defined records for seventy years. Supplied with a matched power supply and bespoke shockmount.',
      specs: [
        { label: 'Capsule', value: 'Large-diaphragm' },
        { label: 'Pattern', value: 'Cardioid (multi-pattern available)' },
        { label: 'Valve', value: 'Hand-selected tube' },
        { label: 'Includes', value: 'PSU, shockmount, case' },
      ],
      provenance: 'Each microphone is hand-built and individually tested against a reference before shipping.',
      gallery: [
        'https://images.unsplash.com/photo-1590602847861-f357a9332bbc',
        'https://images.unsplash.com/photo-1558098329-a11cff621064',
        'https://images.unsplash.com/photo-1545167622-3a6ac756afa4',
      ],
    },
  },
};
